kind: pipeline
name: default

steps:
  - name: build
    image: python:alpine
    commands:
      - pip install pep8
      - pip install pyflakes
      - pep8 webserver.py
      - pyflakes webserver.py
